/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellCitasRouteImport } from './routes/_shell.citas'
import { Route as ShellConfiguracionRouteImport } from './routes/_shell.configuracion'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellPerfilRouteImport } from './routes/_shell.perfil'
import { Route as ShellPersonalRouteImport } from './routes/_shell.personal'
import { Route as ShellProcedimientosRouteImport } from './routes/_shell.procedimientos'
import { Route as ShellReportesRouteImport } from './routes/_shell.reportes'
import { Route as ShellRolesRouteImport } from './routes/_shell.roles'
import { Route as ShellTratamientosRouteImport } from './routes/_shell.tratamientos'
import { Route as ShellUsuariosRouteImport } from './routes/_shell.usuarios'
import { Route as ShellExpedientesIndexRouteImport } from './routes/_shell.expedientes.index'
import { Route as ShellExpedientesIdRouteImport } from './routes/_shell.expedientes.$id'
import { Route as ShellPacientesIndexRouteImport } from './routes/_shell.pacientes.index'
import { Route as ShellPacientesIdRouteImport } from './routes/_shell.pacientes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCitasRoute = ShellCitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConfiguracionRoute = ShellConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPerfilRoute = ShellPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPersonalRoute = ShellPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProcedimientosRoute = ShellProcedimientosRouteImport.update({
  id: '/procedimientos',
  path: '/procedimientos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportesRoute = ShellReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRolesRoute = ShellRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTratamientosRoute = ShellTratamientosRouteImport.update({
  id: '/tratamientos',
  path: '/tratamientos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsuariosRoute = ShellUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExpedientesIndexRoute = ShellExpedientesIndexRouteImport.update({
  id: '/expedientes/',
  path: '/expedientes/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExpedientesIdRoute = ShellExpedientesIdRouteImport.update({
  id: '/expedientes/$id',
  path: '/expedientes/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPacientesIndexRoute = ShellPacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPacientesIdRoute = ShellPacientesIdRouteImport.update({
  id: '/pacientes/$id',
  path: '/pacientes/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citas': typeof ShellCitasRoute
  '/configuracion': typeof ShellConfiguracionRoute
  '/dashboard': typeof ShellDashboardRoute
  '/perfil': typeof ShellPerfilRoute
  '/personal': typeof ShellPersonalRoute
  '/procedimientos': typeof ShellProcedimientosRoute
  '/reportes': typeof ShellReportesRoute
  '/roles': typeof ShellRolesRoute
  '/tratamientos': typeof ShellTratamientosRoute
  '/usuarios': typeof ShellUsuariosRoute
  '/expedientes/$id': typeof ShellExpedientesIdRoute
  '/pacientes/$id': typeof ShellPacientesIdRoute
  '/expedientes/': typeof ShellExpedientesIndexRoute
  '/pacientes/': typeof ShellPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citas': typeof ShellCitasRoute
  '/configuracion': typeof ShellConfiguracionRoute
  '/dashboard': typeof ShellDashboardRoute
  '/perfil': typeof ShellPerfilRoute
  '/personal': typeof ShellPersonalRoute
  '/procedimientos': typeof ShellProcedimientosRoute
  '/reportes': typeof ShellReportesRoute
  '/roles': typeof ShellRolesRoute
  '/tratamientos': typeof ShellTratamientosRoute
  '/usuarios': typeof ShellUsuariosRoute
  '/expedientes/$id': typeof ShellExpedientesIdRoute
  '/pacientes/$id': typeof ShellPacientesIdRoute
  '/expedientes': typeof ShellExpedientesIndexRoute
  '/pacientes': typeof ShellPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/citas': typeof ShellCitasRoute
  '/_shell/configuracion': typeof ShellConfiguracionRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/perfil': typeof ShellPerfilRoute
  '/_shell/personal': typeof ShellPersonalRoute
  '/_shell/procedimientos': typeof ShellProcedimientosRoute
  '/_shell/reportes': typeof ShellReportesRoute
  '/_shell/roles': typeof ShellRolesRoute
  '/_shell/tratamientos': typeof ShellTratamientosRoute
  '/_shell/usuarios': typeof ShellUsuariosRoute
  '/_shell/expedientes/$id': typeof ShellExpedientesIdRoute
  '/_shell/pacientes/$id': typeof ShellPacientesIdRoute
  '/_shell/expedientes/': typeof ShellExpedientesIndexRoute
  '/_shell/pacientes/': typeof ShellPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citas'
    | '/configuracion'
    | '/dashboard'
    | '/perfil'
    | '/personal'
    | '/procedimientos'
    | '/reportes'
    | '/roles'
    | '/tratamientos'
    | '/usuarios'
    | '/expedientes/$id'
    | '/pacientes/$id'
    | '/expedientes/'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citas'
    | '/configuracion'
    | '/dashboard'
    | '/perfil'
    | '/personal'
    | '/procedimientos'
    | '/reportes'
    | '/roles'
    | '/tratamientos'
    | '/usuarios'
    | '/expedientes/$id'
    | '/pacientes/$id'
    | '/expedientes'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/citas'
    | '/_shell/configuracion'
    | '/_shell/dashboard'
    | '/_shell/perfil'
    | '/_shell/personal'
    | '/_shell/procedimientos'
    | '/_shell/reportes'
    | '/_shell/roles'
    | '/_shell/tratamientos'
    | '/_shell/usuarios'
    | '/_shell/expedientes/$id'
    | '/_shell/pacientes/$id'
    | '/_shell/expedientes/'
    | '/_shell/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/citas': {
      id: '/_shell/citas'
      path: '/citas'
      fullPath: '/citas'
      preLoaderRoute: typeof ShellCitasRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/configuracion': {
      id: '/_shell/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ShellConfiguracionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/perfil': {
      id: '/_shell/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof ShellPerfilRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/personal': {
      id: '/_shell/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof ShellPersonalRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/procedimientos': {
      id: '/_shell/procedimientos'
      path: '/procedimientos'
      fullPath: '/procedimientos'
      preLoaderRoute: typeof ShellProcedimientosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reportes': {
      id: '/_shell/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ShellReportesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/roles': {
      id: '/_shell/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof ShellRolesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/tratamientos': {
      id: '/_shell/tratamientos'
      path: '/tratamientos'
      fullPath: '/tratamientos'
      preLoaderRoute: typeof ShellTratamientosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/usuarios': {
      id: '/_shell/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof ShellUsuariosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/expedientes/': {
      id: '/_shell/expedientes/'
      path: '/expedientes'
      fullPath: '/expedientes/'
      preLoaderRoute: typeof ShellExpedientesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/expedientes/$id': {
      id: '/_shell/expedientes/$id'
      path: '/expedientes/$id'
      fullPath: '/expedientes/$id'
      preLoaderRoute: typeof ShellExpedientesIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pacientes/': {
      id: '/_shell/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof ShellPacientesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pacientes/$id': {
      id: '/_shell/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof ShellPacientesIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellCitasRoute: typeof ShellCitasRoute
  ShellConfiguracionRoute: typeof ShellConfiguracionRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellPerfilRoute: typeof ShellPerfilRoute
  ShellPersonalRoute: typeof ShellPersonalRoute
  ShellProcedimientosRoute: typeof ShellProcedimientosRoute
  ShellReportesRoute: typeof ShellReportesRoute
  ShellRolesRoute: typeof ShellRolesRoute
  ShellTratamientosRoute: typeof ShellTratamientosRoute
  ShellUsuariosRoute: typeof ShellUsuariosRoute
  ShellExpedientesIdRoute: typeof ShellExpedientesIdRoute
  ShellPacientesIdRoute: typeof ShellPacientesIdRoute
  ShellExpedientesIndexRoute: typeof ShellExpedientesIndexRoute
  ShellPacientesIndexRoute: typeof ShellPacientesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCitasRoute: ShellCitasRoute,
  ShellConfiguracionRoute: ShellConfiguracionRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellPerfilRoute: ShellPerfilRoute,
  ShellPersonalRoute: ShellPersonalRoute,
  ShellProcedimientosRoute: ShellProcedimientosRoute,
  ShellReportesRoute: ShellReportesRoute,
  ShellRolesRoute: ShellRolesRoute,
  ShellTratamientosRoute: ShellTratamientosRoute,
  ShellUsuariosRoute: ShellUsuariosRoute,
  ShellExpedientesIdRoute: ShellExpedientesIdRoute,
  ShellPacientesIdRoute: ShellPacientesIdRoute,
  ShellExpedientesIndexRoute: ShellExpedientesIndexRoute,
  ShellPacientesIndexRoute: ShellPacientesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
